spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/convenience_shop"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # tự động tạo mới và xóa bảng khi khởi động lại
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  SIGNER_KEY: "wpnKJs8aPIMFcNtNKj5tTjIMReLaGjgisZf8YZMJ8cgw1MCzo3RQfrjFm3D1UINZ"